### ISSUE TITLE
Activity form and Setting page should contain few others input filed.

### ISSUE THREAD

**Issue by sahedbs23** [eLearning-BS23/moodle-mod_html5player#1]
@shadman-ahmed-bs23 

Can you please add 
- aspect ratio 
- responsiveness code for Html5 Player. 

Check Brightcove video sharing option for more details .

**Comment by shadman-ahmed-bs23** [comment]
Okay. Working on it.

**Comment by shadman-ahmed-bs23** [comment]
Code with responsive settings in video-js tag has been pushed to master branch. 

Commit for review: 31bf32896f49462d442372200a9886a6f61d762e 

@sahedbs23 bhai, kindly review the latest commit.
